/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserId = IDL.Nat;
export const Amount = IDL.Nat;
export const VipLevel = IDL.Variant({
  'vip0' : IDL.Null,
  'vip1' : IDL.Null,
  'vip2' : IDL.Null,
  'vip3' : IDL.Null,
});
export const AdminAccountRow = IDL.Record({
  'id' : UserId,
  'balance' : Amount,
  'vipLevel' : VipLevel,
  'blocked' : IDL.Bool,
  'password' : IDL.Text,
  'isOnline' : IDL.Bool,
  'secondaryPassword' : IDL.Text,
  'phone' : IDL.Text,
  'requestedRecharge' : IDL.Opt(Amount),
  'pendingRefund' : Amount,
});
export const Timestamp = IDL.Int;
export const AccountView = IDL.Record({
  'id' : UserId,
  'balance' : Amount,
  'vipLevel' : VipLevel,
  'blocked' : IDL.Bool,
  'createdAt' : Timestamp,
  'isOnline' : IDL.Bool,
  'promoCode' : IDL.Text,
  'creditScore' : IDL.Nat,
  'phone' : IDL.Text,
});
export const SessionView = IDL.Record({
  'account' : AccountView,
  'isAdmin' : IDL.Bool,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalView = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'amount' : Amount,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RecordStatus = IDL.Variant({
  'termine' : IDL.Null,
  'soumission' : IDL.Null,
  'frozen' : IDL.Null,
});
export const TaskRecordView = IDL.Record({
  'id' : IDL.Nat,
  'status' : RecordStatus,
  'thumbnailUrl' : IDL.Text,
  'totalValue' : Amount,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'commission' : Amount,
  'merchant' : IDL.Text,
  'productDescription' : IDL.Text,
});
export const SecondaryPasswordError = IDL.Variant({
  'ok' : IDL.Null,
  'wrongPassword' : IDL.Null,
  'weakPassword' : IDL.Null,
  'notRegistered' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DailyProgress = IDL.Record({
  'insufficientBalance' : IDL.Bool,
  'availableBalance' : Amount,
  'completedToday' : IDL.Nat,
  'vipLevel' : VipLevel,
  'blocked' : IDL.Bool,
  'commissionEarned' : Amount,
  'canStartTask' : IDL.Bool,
  'commissionRate' : IDL.Nat,
  'requestedRecharge' : IDL.Opt(Amount),
  'pendingRefund' : Amount,
  'dailyTaskQuota' : IDL.Nat,
});
export const ServiceStatus = IDL.Record({
  'closesAtHour' : IDL.Nat,
  'isOpen' : IDL.Bool,
  'opensAtHour' : IDL.Nat,
});
export const CommissionEntry = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : Amount,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AttachmentKind = IDL.Variant({
  'video' : IDL.Null,
  'file' : IDL.Null,
  'image' : IDL.Null,
});
export const Attachment = IDL.Record({
  'blob' : ExternalBlob,
  'kind' : AttachmentKind,
  'name' : IDL.Text,
  'size' : IDL.Nat,
});
export const ChatMessageView = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'fromAdmin' : IDL.Bool,
  'attachment' : IDL.Opt(Attachment),
});
export const ConversationSummary = IDL.Record({
  'lastMessageAt' : Timestamp,
  'userId' : UserId,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
  'phone' : IDL.Text,
});
export const VipConfig = IDL.Record({
  'level' : VipLevel,
  'commissionRate' : IDL.Nat,
  'dailyTaskQuota' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addMoney' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [SessionView], []),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalView], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTaskToUser' : IDL.Func(
      [UserId, IDL.Text, IDL.Text, IDL.Text, Amount],
      [TaskRecordView],
      [],
    ),
  'assignTaskToVip' : IDL.Func(
      [VipLevel, IDL.Text, IDL.Text, IDL.Text, Amount],
      [IDL.Vec(TaskRecordView)],
      [],
    ),
  'changeSecondaryPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [SecondaryPasswordError],
      [],
    ),
  'clearConversation' : IDL.Func([UserId], [], []),
  'creditRecharge' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyProgress' : IDL.Func([], [DailyProgress], ['query']),
  'getMyAccount' : IDL.Func([], [IDL.Opt(AccountView)], ['query']),
  'getRecord' : IDL.Func([IDL.Nat], [IDL.Opt(TaskRecordView)], ['query']),
  'getServiceStatus' : IDL.Func([], [ServiceStatus], ['query']),
  'grantCommission' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAccounts' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(AdminAccountRow)],
      ['query'],
    ),
  'listCommissions' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(CommissionEntry)],
      ['query'],
    ),
  'listConversationMessages' : IDL.Func(
      [UserId, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(ChatMessageView)],
      ['query'],
    ),
  'listConversations' : IDL.Func(
      [IDL.Nat, IDL.Opt(UserId)],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'listMyMessages' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(ChatMessageView)],
      ['query'],
    ),
  'listMyWithdrawals' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(WithdrawalView)],
      ['query'],
    ),
  'listPendingWithdrawals' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(WithdrawalView)],
      ['query'],
    ),
  'listRecords' : IDL.Func(
      [IDL.Opt(RecordStatus), IDL.Nat, IDL.Opt(IDL.Nat)],
      [IDL.Vec(TaskRecordView)],
      ['query'],
    ),
  'listVipConfigs' : IDL.Func([], [IDL.Vec(VipConfig)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [SessionView], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AccountView],
      [],
    ),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalView], []),
  'removeMoney' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'replyToUser' : IDL.Func(
      [UserId, IDL.Text, IDL.Opt(Attachment)],
      [ChatMessageView],
      [],
    ),
  'requestWithdrawal' : IDL.Func([Amount, IDL.Text], [WithdrawalView], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Opt(Attachment)],
      [ChatMessageView],
      [],
    ),
  'setAccountBlocked' : IDL.Func([UserId, IDL.Bool], [AdminAccountRow], []),
  'setPendingRefund' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'setRechargeRequest' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
  'setSecondaryPassword' : IDL.Func([UserId, IDL.Text], [AdminAccountRow], []),
  'setVipConfig' : IDL.Func([VipLevel, IDL.Nat, IDL.Nat], [VipConfig], []),
  'setVipLevel' : IDL.Func([UserId, VipLevel], [AdminAccountRow], []),
  'startTask' : IDL.Func([], [TaskRecordView], []),
  'touchSession' : IDL.Func([], [IDL.Opt(AccountView)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserId = IDL.Nat;
  const Amount = IDL.Nat;
  const VipLevel = IDL.Variant({
    'vip0' : IDL.Null,
    'vip1' : IDL.Null,
    'vip2' : IDL.Null,
    'vip3' : IDL.Null,
  });
  const AdminAccountRow = IDL.Record({
    'id' : UserId,
    'balance' : Amount,
    'vipLevel' : VipLevel,
    'blocked' : IDL.Bool,
    'password' : IDL.Text,
    'isOnline' : IDL.Bool,
    'secondaryPassword' : IDL.Text,
    'phone' : IDL.Text,
    'requestedRecharge' : IDL.Opt(Amount),
    'pendingRefund' : Amount,
  });
  const Timestamp = IDL.Int;
  const AccountView = IDL.Record({
    'id' : UserId,
    'balance' : Amount,
    'vipLevel' : VipLevel,
    'blocked' : IDL.Bool,
    'createdAt' : Timestamp,
    'isOnline' : IDL.Bool,
    'promoCode' : IDL.Text,
    'creditScore' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const SessionView = IDL.Record({
    'account' : AccountView,
    'isAdmin' : IDL.Bool,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalView = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'amount' : Amount,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RecordStatus = IDL.Variant({
    'termine' : IDL.Null,
    'soumission' : IDL.Null,
    'frozen' : IDL.Null,
  });
  const TaskRecordView = IDL.Record({
    'id' : IDL.Nat,
    'status' : RecordStatus,
    'thumbnailUrl' : IDL.Text,
    'totalValue' : Amount,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'commission' : Amount,
    'merchant' : IDL.Text,
    'productDescription' : IDL.Text,
  });
  const SecondaryPasswordError = IDL.Variant({
    'ok' : IDL.Null,
    'wrongPassword' : IDL.Null,
    'weakPassword' : IDL.Null,
    'notRegistered' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DailyProgress = IDL.Record({
    'insufficientBalance' : IDL.Bool,
    'availableBalance' : Amount,
    'completedToday' : IDL.Nat,
    'vipLevel' : VipLevel,
    'blocked' : IDL.Bool,
    'commissionEarned' : Amount,
    'canStartTask' : IDL.Bool,
    'commissionRate' : IDL.Nat,
    'requestedRecharge' : IDL.Opt(Amount),
    'pendingRefund' : Amount,
    'dailyTaskQuota' : IDL.Nat,
  });
  const ServiceStatus = IDL.Record({
    'closesAtHour' : IDL.Nat,
    'isOpen' : IDL.Bool,
    'opensAtHour' : IDL.Nat,
  });
  const CommissionEntry = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'amount' : Amount,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AttachmentKind = IDL.Variant({
    'video' : IDL.Null,
    'file' : IDL.Null,
    'image' : IDL.Null,
  });
  const Attachment = IDL.Record({
    'blob' : ExternalBlob,
    'kind' : AttachmentKind,
    'name' : IDL.Text,
    'size' : IDL.Nat,
  });
  const ChatMessageView = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'fromAdmin' : IDL.Bool,
    'attachment' : IDL.Opt(Attachment),
  });
  const ConversationSummary = IDL.Record({
    'lastMessageAt' : Timestamp,
    'userId' : UserId,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const VipConfig = IDL.Record({
    'level' : VipLevel,
    'commissionRate' : IDL.Nat,
    'dailyTaskQuota' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addMoney' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [SessionView], []),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalView], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTaskToUser' : IDL.Func(
        [UserId, IDL.Text, IDL.Text, IDL.Text, Amount],
        [TaskRecordView],
        [],
      ),
    'assignTaskToVip' : IDL.Func(
        [VipLevel, IDL.Text, IDL.Text, IDL.Text, Amount],
        [IDL.Vec(TaskRecordView)],
        [],
      ),
    'changeSecondaryPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SecondaryPasswordError],
        [],
      ),
    'clearConversation' : IDL.Func([UserId], [], []),
    'creditRecharge' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyProgress' : IDL.Func([], [DailyProgress], ['query']),
    'getMyAccount' : IDL.Func([], [IDL.Opt(AccountView)], ['query']),
    'getRecord' : IDL.Func([IDL.Nat], [IDL.Opt(TaskRecordView)], ['query']),
    'getServiceStatus' : IDL.Func([], [ServiceStatus], ['query']),
    'grantCommission' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAccounts' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(AdminAccountRow)],
        ['query'],
      ),
    'listCommissions' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(CommissionEntry)],
        ['query'],
      ),
    'listConversationMessages' : IDL.Func(
        [UserId, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(ChatMessageView)],
        ['query'],
      ),
    'listConversations' : IDL.Func(
        [IDL.Nat, IDL.Opt(UserId)],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'listMyMessages' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(ChatMessageView)],
        ['query'],
      ),
    'listMyWithdrawals' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(WithdrawalView)],
        ['query'],
      ),
    'listPendingWithdrawals' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(WithdrawalView)],
        ['query'],
      ),
    'listRecords' : IDL.Func(
        [IDL.Opt(RecordStatus), IDL.Nat, IDL.Opt(IDL.Nat)],
        [IDL.Vec(TaskRecordView)],
        ['query'],
      ),
    'listVipConfigs' : IDL.Func([], [IDL.Vec(VipConfig)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [SessionView], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AccountView],
        [],
      ),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalView], []),
    'removeMoney' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'replyToUser' : IDL.Func(
        [UserId, IDL.Text, IDL.Opt(Attachment)],
        [ChatMessageView],
        [],
      ),
    'requestWithdrawal' : IDL.Func([Amount, IDL.Text], [WithdrawalView], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Opt(Attachment)],
        [ChatMessageView],
        [],
      ),
    'setAccountBlocked' : IDL.Func([UserId, IDL.Bool], [AdminAccountRow], []),
    'setPendingRefund' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'setRechargeRequest' : IDL.Func([UserId, Amount], [AdminAccountRow], []),
    'setSecondaryPassword' : IDL.Func(
        [UserId, IDL.Text],
        [AdminAccountRow],
        [],
      ),
    'setVipConfig' : IDL.Func([VipLevel, IDL.Nat, IDL.Nat], [VipConfig], []),
    'setVipLevel' : IDL.Func([UserId, VipLevel], [AdminAccountRow], []),
    'startTask' : IDL.Func([], [TaskRecordView], []),
    'touchSession' : IDL.Func([], [IDL.Opt(AccountView)], []),
  });
};

export const init = ({ IDL }) => { return []; };