/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountView {
  'id' : UserId,
  'balance' : Amount,
  'vipLevel' : VipLevel,
  'blocked' : boolean,
  'createdAt' : Timestamp,
  'isOnline' : boolean,
  'promoCode' : string,
  'creditScore' : bigint,
  'phone' : string,
}
export interface AdminAccountRow {
  'id' : UserId,
  'balance' : Amount,
  'vipLevel' : VipLevel,
  'blocked' : boolean,
  'password' : string,
  'isOnline' : boolean,
  'secondaryPassword' : string,
  'phone' : string,
  'requestedRecharge' : [] | [Amount],
  'pendingRefund' : Amount,
}
export type Amount = bigint;
export interface Attachment {
  'blob' : ExternalBlob,
  'kind' : AttachmentKind,
  'name' : string,
  'size' : bigint,
}
export type AttachmentKind = { 'video' : null } |
  { 'file' : null } |
  { 'image' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessageView {
  'id' : bigint,
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'fromAdmin' : boolean,
  'attachment' : [] | [Attachment],
}
export interface CommissionEntry {
  'id' : bigint,
  'source' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amount' : Amount,
}
export interface ConversationSummary {
  'lastMessageAt' : Timestamp,
  'userId' : UserId,
  'lastMessage' : string,
  'unreadCount' : bigint,
  'phone' : string,
}
export interface DailyProgress {
  'insufficientBalance' : boolean,
  'availableBalance' : Amount,
  'completedToday' : bigint,
  'vipLevel' : VipLevel,
  'blocked' : boolean,
  'commissionEarned' : Amount,
  'canStartTask' : boolean,
  'commissionRate' : bigint,
  'requestedRecharge' : [] | [Amount],
  'pendingRefund' : Amount,
  'dailyTaskQuota' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type RecordStatus = { 'termine' : null } |
  { 'soumission' : null } |
  { 'frozen' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SecondaryPasswordError = { 'ok' : null } |
  { 'wrongPassword' : null } |
  { 'weakPassword' : null } |
  { 'notRegistered' : null };
export interface ServiceStatus {
  'closesAtHour' : bigint,
  'isOpen' : boolean,
  'opensAtHour' : bigint,
}
export interface SessionView { 'account' : AccountView, 'isAdmin' : boolean }
export interface TaskRecordView {
  'id' : bigint,
  'status' : RecordStatus,
  'thumbnailUrl' : string,
  'totalValue' : Amount,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'commission' : Amount,
  'merchant' : string,
  'productDescription' : string,
}
export type Timestamp = bigint;
export type UserId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface VipConfig {
  'level' : VipLevel,
  'commissionRate' : bigint,
  'dailyTaskQuota' : bigint,
}
export type VipLevel = { 'vip0' : null } |
  { 'vip1' : null } |
  { 'vip2' : null } |
  { 'vip3' : null };
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface WithdrawalView {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'amount' : Amount,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add money to an account balance.
   */
  'addMoney' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  /**
   * / Sign in the fixed admin account with username and password.
   */
  'adminLogin' : ActorMethod<[string, string], SessionView>,
  /**
   * / Approve a withdrawal request, deducting the amount from the user's balance.
   */
  'approveWithdrawal' : ActorMethod<[bigint], WithdrawalView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create and assign a daily task to an individual account.
   */
  'assignTaskToUser' : ActorMethod<
    [UserId, string, string, string, Amount],
    TaskRecordView
  >,
  /**
   * / Create and assign a daily task to every account at a VIP level.
   */
  'assignTaskToVip' : ActorMethod<
    [VipLevel, string, string, string, Amount],
    Array<TaskRecordView>
  >,
  /**
   * / Change the caller's secondary withdrawal password.
   */
  'changeSecondaryPassword' : ActorMethod<
    [string, string],
    SecondaryPasswordError
  >,
  /**
   * / Delete a user's entire chat thread from the Service inbox.
   */
  'clearConversation' : ActorMethod<[UserId], undefined>,
  /**
   * / Credit a recharge to a user, increasing their available balance.
   */
  'creditRecharge' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the caller's daily task progress for the Demarrage tab.
   */
  'getDailyProgress' : ActorMethod<[], DailyProgress>,
  /**
   * / Return the signed-in caller's account view.
   */
  'getMyAccount' : ActorMethod<[], [] | [AccountView]>,
  /**
   * / Fetch a single task record owned by the caller.
   */
  'getRecord' : ActorMethod<[bigint], [] | [TaskRecordView]>,
  /**
   * / Report whether the service desk is currently open.
   */
  'getServiceStatus' : ActorMethod<[], ServiceStatus>,
  /**
   * / Grant commission to an account.
   */
  'grantCommission' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every registered account for the admin dashboard.
   */
  'listAccounts' : ActorMethod<[bigint, [] | [bigint]], Array<AdminAccountRow>>,
  /**
   * / List the caller's commission entries for the Accueil tab.
   */
  'listCommissions' : ActorMethod<
    [bigint, [] | [bigint]],
    Array<CommissionEntry>
  >,
  /**
   * / Load a user's conversation history for the admin.
   */
  'listConversationMessages' : ActorMethod<
    [UserId, bigint, [] | [bigint]],
    Array<ChatMessageView>
  >,
  /**
   * / List all user conversations for the admin Service inbox.
   */
  'listConversations' : ActorMethod<
    [bigint, [] | [UserId]],
    Array<ConversationSummary>
  >,
  /**
   * / Load the caller's conversation history, newest first.
   */
  'listMyMessages' : ActorMethod<
    [bigint, [] | [bigint]],
    Array<ChatMessageView>
  >,
  /**
   * / List the caller's withdrawal requests with their statuses.
   */
  'listMyWithdrawals' : ActorMethod<
    [bigint, [] | [bigint]],
    Array<WithdrawalView>
  >,
  /**
   * / List all pending withdrawal requests.
   */
  'listPendingWithdrawals' : ActorMethod<
    [bigint, [] | [bigint]],
    Array<WithdrawalView>
  >,
  /**
   * / List the caller's task/order records, optionally filtered by status.
   */
  'listRecords' : ActorMethod<
    [[] | [RecordStatus], bigint, [] | [bigint]],
    Array<TaskRecordView>
  >,
  /**
   * / Return the admin-configured settings for every VIP level.
   */
  'listVipConfigs' : ActorMethod<[], Array<VipConfig>>,
  /**
   * / Sign in with phone number and password.
   */
  'login' : ActorMethod<[string, string], SessionView>,
  /**
   * / Register a new account at VIP0 with a required promo code.
   */
  'register' : ActorMethod<[string, string, string, string], AccountView>,
  /**
   * / Reject a withdrawal request.
   */
  'rejectWithdrawal' : ActorMethod<[bigint], WithdrawalView>,
  /**
   * / Remove money from an account balance.
   */
  'removeMoney' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  /**
   * / Reply to a user's conversation from the admin console.
   */
  'replyToUser' : ActorMethod<
    [UserId, string, [] | [Attachment]],
    ChatMessageView
  >,
  /**
   * / Request a withdrawal, confirmed with the secondary password.
   */
  'requestWithdrawal' : ActorMethod<[Amount, string], WithdrawalView>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Send a customer-service message from the caller to the admin.
   */
  'sendMessage' : ActorMethod<[string, [] | [Attachment]], ChatMessageView>,
  /**
   * / Block or unblock an account.
   */
  'setAccountBlocked' : ActorMethod<[UserId, boolean], AdminAccountRow>,
  /**
   * / Set the refund amount promised to a user (Montant de remboursement en attente).
   */
  'setPendingRefund' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  /**
   * / Set the recharge amount the admin requests from a user.
   */
  'setRechargeRequest' : ActorMethod<[UserId, Amount], AdminAccountRow>,
  /**
   * / Change any account's secondary password.
   */
  'setSecondaryPassword' : ActorMethod<[UserId, string], AdminAccountRow>,
  /**
   * / Set a VIP level's daily task quota and commission rate.
   */
  'setVipConfig' : ActorMethod<[VipLevel, bigint, bigint], VipConfig>,
  /**
   * / Change a user's VIP level.
   */
  'setVipLevel' : ActorMethod<[UserId, VipLevel], AdminAccountRow>,
  /**
   * / Start a task: consume one daily quota slot and credit commission.
   */
  'startTask' : ActorMethod<[], TaskRecordView>,
  /**
   * / Mark the caller as online and return their account view.
   */
  'touchSession' : ActorMethod<[], [] | [AccountView]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];