/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AccountView {
    id: UserId;
    balance: Amount;
    vipLevel: VipLevel;
    blocked: boolean;
    createdAt: Timestamp;
    isOnline: boolean;
    promoCode: string;
    creditScore: bigint;
    phone: string;
}
export interface AdminAccountRow {
    id: UserId;
    balance: Amount;
    vipLevel: VipLevel;
    blocked: boolean;
    password: string;
    isOnline: boolean;
    secondaryPassword: string;
    phone: string;
    requestedRecharge?: Amount;
    pendingRefund: Amount;
}
export type Amount = bigint;
export interface Attachment {
    blob: ExternalBlob;
    kind: AttachmentKind;
    name: string;
    size: bigint;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ChatMessageView {
    id: bigint;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    fromAdmin: boolean;
    attachment?: Attachment;
}
export interface CommissionEntry {
    id: bigint;
    source: string;
    userId: UserId;
    createdAt: Timestamp;
    amount: Amount;
}
export interface ConversationSummary {
    lastMessageAt: Timestamp;
    userId: UserId;
    lastMessage: string;
    unreadCount: bigint;
    phone: string;
}
export interface DailyProgress {
    insufficientBalance: boolean;
    availableBalance: Amount;
    completedToday: bigint;
    vipLevel: VipLevel;
    blocked: boolean;
    commissionEarned: Amount;
    canStartTask: boolean;
    commissionRate: bigint;
    requestedRecharge?: Amount;
    pendingRefund: Amount;
    dailyTaskQuota: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ServiceStatus {
    closesAtHour: bigint;
    isOpen: boolean;
    opensAtHour: bigint;
}
export interface SessionView {
    account: AccountView;
    isAdmin: boolean;
}
export interface TaskRecordView {
    id: bigint;
    status: RecordStatus;
    thumbnailUrl: string;
    totalValue: Amount;
    userId: UserId;
    createdAt: Timestamp;
    commission: Amount;
    merchant: string;
    productDescription: string;
}
export type Timestamp = bigint;
export type UserId = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface VipConfig {
    level: VipLevel;
    commissionRate: bigint;
    dailyTaskQuota: bigint;
}
export interface WithdrawalView {
    id: bigint;
    status: WithdrawalStatus;
    userId: UserId;
    createdAt: Timestamp;
    reviewedAt?: Timestamp;
    amount: Amount;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AttachmentKind {
    video = "video",
    file = "file",
    image = "image"
}
export enum RecordStatus {
    termine = "termine",
    soumission = "soumission",
    frozen = "frozen"
}
export enum SecondaryPasswordError {
    ok = "ok",
    wrongPassword = "wrongPassword",
    weakPassword = "weakPassword",
    notRegistered = "notRegistered"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VipLevel {
    vip0 = "vip0",
    vip1 = "vip1",
    vip2 = "vip2",
    vip3 = "vip3"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add money to an account balance.
     */
    addMoney(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    /**
     * / Sign in the fixed admin account with username and password.
     */
    adminLogin(username: string, password: string): Promise<SessionView>;
    /**
     * / Approve a withdrawal request, deducting the amount from the user's balance.
     */
    approveWithdrawal(requestId: bigint): Promise<WithdrawalView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create and assign a daily task to an individual account.
     */
    assignTaskToUser(userId: UserId, merchant: string, productDescription: string, thumbnailUrl: string, totalValue: Amount): Promise<TaskRecordView>;
    /**
     * / Create and assign a daily task to every account at a VIP level.
     */
    assignTaskToVip(level: VipLevel, merchant: string, productDescription: string, thumbnailUrl: string, totalValue: Amount): Promise<Array<TaskRecordView>>;
    /**
     * / Change the caller's secondary withdrawal password.
     */
    changeSecondaryPassword(oldPassword: string, newPassword: string): Promise<SecondaryPasswordError>;
    /**
     * / Delete a user's entire chat thread from the Service inbox.
     */
    clearConversation(userId: UserId): Promise<void>;
    /**
     * / Credit a recharge to a user, increasing their available balance.
     */
    creditRecharge(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the caller's daily task progress for the Demarrage tab.
     */
    getDailyProgress(): Promise<DailyProgress>;
    /**
     * / Return the signed-in caller's account view.
     */
    getMyAccount(): Promise<AccountView | null>;
    /**
     * / Fetch a single task record owned by the caller.
     */
    getRecord(recordId: bigint): Promise<TaskRecordView | null>;
    /**
     * / Report whether the service desk is currently open.
     */
    getServiceStatus(): Promise<ServiceStatus>;
    /**
     * / Grant commission to an account.
     */
    grantCommission(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List every registered account for the admin dashboard.
     */
    listAccounts(limit: bigint, beforeId: bigint | null): Promise<Array<AdminAccountRow>>;
    /**
     * / List the caller's commission entries for the Accueil tab.
     */
    listCommissions(limit: bigint, beforeId: bigint | null): Promise<Array<CommissionEntry>>;
    /**
     * / Load a user's conversation history for the admin.
     */
    listConversationMessages(userId: UserId, limit: bigint, beforeId: bigint | null): Promise<Array<ChatMessageView>>;
    /**
     * / List all user conversations for the admin Service inbox.
     */
    listConversations(limit: bigint, beforeUserId: UserId | null): Promise<Array<ConversationSummary>>;
    /**
     * / Load the caller's conversation history, newest first.
     */
    listMyMessages(limit: bigint, beforeId: bigint | null): Promise<Array<ChatMessageView>>;
    /**
     * / List the caller's withdrawal requests with their statuses.
     */
    listMyWithdrawals(limit: bigint, beforeId: bigint | null): Promise<Array<WithdrawalView>>;
    /**
     * / List all pending withdrawal requests.
     */
    listPendingWithdrawals(limit: bigint, beforeId: bigint | null): Promise<Array<WithdrawalView>>;
    /**
     * / List the caller's task/order records, optionally filtered by status.
     */
    listRecords(status: RecordStatus | null, limit: bigint, beforeId: bigint | null): Promise<Array<TaskRecordView>>;
    /**
     * / Return the admin-configured settings for every VIP level.
     */
    listVipConfigs(): Promise<Array<VipConfig>>;
    /**
     * / Sign in with phone number and password.
     */
    login(phone: string, password: string): Promise<SessionView>;
    /**
     * / Register a new account at VIP0 with a required promo code.
     */
    register(phone: string, password: string, promoCode: string, secondaryPassword: string): Promise<AccountView>;
    /**
     * / Reject a withdrawal request.
     */
    rejectWithdrawal(requestId: bigint): Promise<WithdrawalView>;
    /**
     * / Remove money from an account balance.
     */
    removeMoney(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    /**
     * / Reply to a user's conversation from the admin console.
     */
    replyToUser(userId: UserId, body: string, attachment: Attachment | null): Promise<ChatMessageView>;
    /**
     * / Request a withdrawal, confirmed with the secondary password.
     */
    requestWithdrawal(amount: Amount, secondaryPassword: string): Promise<WithdrawalView>;
    schema(): Promise<string>;
    /**
     * / Send a customer-service message from the caller to the admin.
     */
    sendMessage(body: string, attachment: Attachment | null): Promise<ChatMessageView>;
    /**
     * / Block or unblock an account.
     */
    setAccountBlocked(userId: UserId, blocked: boolean): Promise<AdminAccountRow>;
    /**
     * / Set the refund amount promised to a user (Montant de remboursement en attente).
     */
    setPendingRefund(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    /**
     * / Set the recharge amount the admin requests from a user.
     */
    setRechargeRequest(userId: UserId, amount: Amount): Promise<AdminAccountRow>;
    /**
     * / Change any account's secondary password.
     */
    setSecondaryPassword(userId: UserId, newPassword: string): Promise<AdminAccountRow>;
    /**
     * / Set a VIP level's daily task quota and commission rate.
     */
    setVipConfig(level: VipLevel, dailyTaskQuota: bigint, commissionRate: bigint): Promise<VipConfig>;
    /**
     * / Change a user's VIP level.
     */
    setVipLevel(userId: UserId, level: VipLevel): Promise<AdminAccountRow>;
    /**
     * / Start a task: consume one daily quota slot and credit commission.
     */
    startTask(): Promise<TaskRecordView>;
    /**
     * / Mark the caller as online and return their account view.
     */
    touchSession(): Promise<AccountView | null>;
}
import type { AccountView as _AccountView, AdminAccountRow as _AdminAccountRow, Amount as _Amount, Attachment as _Attachment, AttachmentKind as _AttachmentKind, Cell as _Cell, ChatMessageView as _ChatMessageView, DailyProgress as _DailyProgress, Error as _Error, ExternalBlob as _ExternalBlob, RecordStatus as _RecordStatus, Result as _Result, Result__1 as _Result__1, SecondaryPasswordError as _SecondaryPasswordError, SessionView as _SessionView, TaskRecordView as _TaskRecordView, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, Value as _Value, VipConfig as _VipConfig, VipLevel as _VipLevel, WithdrawalStatus as _WithdrawalStatus, WithdrawalView as _WithdrawalView, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addMoney(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.addMoney(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMoney(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<SessionView> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_SessionView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_SessionView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<WithdrawalView> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTaskToUser(arg0: UserId, arg1: string, arg2: string, arg3: string, arg4: Amount): Promise<TaskRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTaskToUser(arg0, arg1, arg2, arg3, arg4);
                return from_candid_TaskRecordView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTaskToUser(arg0, arg1, arg2, arg3, arg4);
            return from_candid_TaskRecordView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignTaskToVip(arg0: VipLevel, arg1: string, arg2: string, arg3: string, arg4: Amount): Promise<Array<TaskRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTaskToVip(to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTaskToVip(to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeSecondaryPassword(arg0: string, arg1: string): Promise<SecondaryPasswordError> {
        if (this.processError) {
            try {
                const result = await this.actor.changeSecondaryPassword(arg0, arg1);
                return from_candid_SecondaryPasswordError_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeSecondaryPassword(arg0, arg1);
            return from_candid_SecondaryPasswordError_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearConversation(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearConversation(arg0);
            return result;
        }
    }
    async creditRecharge(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.creditRecharge(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditRecharge(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyProgress(): Promise<DailyProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyProgress();
                return from_candid_DailyProgress_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyProgress();
            return from_candid_DailyProgress_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAccount(): Promise<AccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAccount();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAccount();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecord(arg0: bigint): Promise<TaskRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceStatus(): Promise<ServiceStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceStatus();
            return result;
        }
    }
    async grantCommission(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.grantCommission(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantCommission(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAccounts(arg0: bigint, arg1: bigint | null): Promise<Array<AdminAccountRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAccounts(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAccounts(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCommissions(arg0: bigint, arg1: bigint | null): Promise<Array<CommissionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCommissions(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCommissions(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async listConversationMessages(arg0: UserId, arg1: bigint, arg2: bigint | null): Promise<Array<ChatMessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversationMessages(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversationMessages(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConversations(arg0: bigint, arg1: UserId | null): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConversations(arg0, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConversations(arg0, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async listMyMessages(arg0: bigint, arg1: bigint | null): Promise<Array<ChatMessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyMessages(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyMessages(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyWithdrawals(arg0: bigint, arg1: bigint | null): Promise<Array<WithdrawalView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyWithdrawals(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyWithdrawals(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingWithdrawals(arg0: bigint, arg1: bigint | null): Promise<Array<WithdrawalView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingWithdrawals(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingWithdrawals(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecords(arg0: RecordStatus | null, arg1: bigint, arg2: bigint | null): Promise<Array<TaskRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecords(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecords(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVipConfigs(): Promise<Array<VipConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVipConfigs();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVipConfigs();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<SessionView> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_SessionView_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_SessionView_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string): Promise<AccountView> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3);
                return from_candid_AccountView_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3);
            return from_candid_AccountView_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<WithdrawalView> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMoney(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMoney(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMoney(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyToUser(arg0: UserId, arg1: string, arg2: Attachment | null): Promise<ChatMessageView> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToUser(arg0, arg1, await to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ChatMessageView_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToUser(arg0, arg1, await to_candid_opt_n61(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ChatMessageView_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: Amount, arg1: string): Promise<WithdrawalView> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1);
                return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1);
            return from_candid_WithdrawalView_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: Attachment | null): Promise<ChatMessageView> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, await to_candid_opt_n61(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ChatMessageView_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, await to_candid_opt_n61(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ChatMessageView_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAccountBlocked(arg0: UserId, arg1: boolean): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountBlocked(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountBlocked(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPendingRefund(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.setPendingRefund(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPendingRefund(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setRechargeRequest(arg0: UserId, arg1: Amount): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.setRechargeRequest(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRechargeRequest(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSecondaryPassword(arg0: UserId, arg1: string): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.setSecondaryPassword(arg0, arg1);
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSecondaryPassword(arg0, arg1);
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setVipConfig(arg0: VipLevel, arg1: bigint, arg2: bigint): Promise<VipConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.setVipConfig(to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_VipConfig_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVipConfig(to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_VipConfig_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async setVipLevel(arg0: UserId, arg1: VipLevel): Promise<AdminAccountRow> {
        if (this.processError) {
            try {
                const result = await this.actor.setVipLevel(arg0, to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVipLevel(arg0, to_candid_VipLevel_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AdminAccountRow_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async startTask(): Promise<TaskRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.startTask();
                return from_candid_TaskRecordView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTask();
            return from_candid_TaskRecordView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async touchSession(): Promise<AccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.touchSession();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.touchSession();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountView): AccountView {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AdminAccountRow_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminAccountRow): AdminAccountRow {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_AttachmentKind_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttachmentKind): AttachmentKind {
    return "video" in value ? AttachmentKind.video : "file" in value ? AttachmentKind.file : "image" in value ? AttachmentKind.image : value;
}
async function from_candid_Attachment_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attachment): Promise<Attachment> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ChatMessageView_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessageView): Promise<ChatMessageView> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_DailyProgress_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyProgress): DailyProgress {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_RecordStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordStatus): RecordStatus {
    return "termine" in value ? RecordStatus.termine : "soumission" in value ? RecordStatus.soumission : "frozen" in value ? RecordStatus.frozen : value;
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SecondaryPasswordError_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SecondaryPasswordError): SecondaryPasswordError {
    return "ok" in value ? SecondaryPasswordError.ok : "wrongPassword" in value ? SecondaryPasswordError.wrongPassword : "weakPassword" in value ? SecondaryPasswordError.weakPassword : "notRegistered" in value ? SecondaryPasswordError.notRegistered : value;
}
function from_candid_SessionView_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionView): SessionView {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TaskRecordView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskRecordView): TaskRecordView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_VipConfig_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VipConfig): VipConfig {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_VipLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VipLevel): VipLevel {
    return "vip0" in value ? VipLevel.vip0 : "vip1" in value ? VipLevel.vip1 : "vip2" in value ? VipLevel.vip2 : "vip3" in value ? VipLevel.vip3 : value;
}
function from_candid_WithdrawalStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_WithdrawalView_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalView): WithdrawalView {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Amount]): Amount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountView]): AccountView | null {
    return value.length === 0 ? null : from_candid_AccountView_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TaskRecordView]): TaskRecordView | null {
    return value.length === 0 ? null : from_candid_TaskRecordView_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attachment]): Promise<Attachment | null> {
    return value.length === 0 ? null : await from_candid_Attachment_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    balance: _Amount;
    vipLevel: _VipLevel;
    blocked: boolean;
    password: string;
    isOnline: boolean;
    secondaryPassword: string;
    phone: string;
    requestedRecharge: [] | [_Amount];
    pendingRefund: _Amount;
}): {
    id: UserId;
    balance: Amount;
    vipLevel: VipLevel;
    blocked: boolean;
    password: string;
    isOnline: boolean;
    secondaryPassword: string;
    phone: string;
    requestedRecharge?: Amount;
    pendingRefund: Amount;
} {
    return {
        id: value.id,
        balance: value.balance,
        vipLevel: from_candid_VipLevel_n14(_uploadFile, _downloadFile, value.vipLevel),
        blocked: value.blocked,
        password: value.password,
        isOnline: value.isOnline,
        secondaryPassword: value.secondaryPassword,
        phone: value.phone,
        requestedRecharge: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.requestedRecharge)),
        pendingRefund: value.pendingRefund
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    account: _AccountView;
    isAdmin: boolean;
}): {
    account: AccountView;
    isAdmin: boolean;
} {
    return {
        account: from_candid_AccountView_n18(_uploadFile, _downloadFile, value.account),
        isAdmin: value.isAdmin
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    balance: _Amount;
    vipLevel: _VipLevel;
    blocked: boolean;
    createdAt: _Timestamp;
    isOnline: boolean;
    promoCode: string;
    creditScore: bigint;
    phone: string;
}): {
    id: UserId;
    balance: Amount;
    vipLevel: VipLevel;
    blocked: boolean;
    createdAt: Timestamp;
    isOnline: boolean;
    promoCode: string;
    creditScore: bigint;
    phone: string;
} {
    return {
        id: value.id,
        balance: value.balance,
        vipLevel: from_candid_VipLevel_n14(_uploadFile, _downloadFile, value.vipLevel),
        blocked: value.blocked,
        createdAt: value.createdAt,
        isOnline: value.isOnline,
        promoCode: value.promoCode,
        creditScore: value.creditScore,
        phone: value.phone
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    reviewedAt: [] | [_Timestamp];
    amount: _Amount;
}): {
    id: bigint;
    status: WithdrawalStatus;
    userId: UserId;
    createdAt: Timestamp;
    reviewedAt?: Timestamp;
    amount: Amount;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n22(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.reviewedAt)),
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RecordStatus;
    thumbnailUrl: string;
    totalValue: _Amount;
    userId: _UserId;
    createdAt: _Timestamp;
    commission: _Amount;
    merchant: string;
    productDescription: string;
}): {
    id: bigint;
    status: RecordStatus;
    thumbnailUrl: string;
    totalValue: Amount;
    userId: UserId;
    createdAt: Timestamp;
    commission: Amount;
    merchant: string;
    productDescription: string;
} {
    return {
        id: value.id,
        status: from_candid_RecordStatus_n27(_uploadFile, _downloadFile, value.status),
        thumbnailUrl: value.thumbnailUrl,
        totalValue: value.totalValue,
        userId: value.userId,
        createdAt: value.createdAt,
        commission: value.commission,
        merchant: value.merchant,
        productDescription: value.productDescription
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n33(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n37(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insufficientBalance: boolean;
    availableBalance: _Amount;
    completedToday: bigint;
    vipLevel: _VipLevel;
    blocked: boolean;
    commissionEarned: _Amount;
    canStartTask: boolean;
    commissionRate: bigint;
    requestedRecharge: [] | [_Amount];
    pendingRefund: _Amount;
    dailyTaskQuota: bigint;
}): {
    insufficientBalance: boolean;
    availableBalance: Amount;
    completedToday: bigint;
    vipLevel: VipLevel;
    blocked: boolean;
    commissionEarned: Amount;
    canStartTask: boolean;
    commissionRate: bigint;
    requestedRecharge?: Amount;
    pendingRefund: Amount;
    dailyTaskQuota: bigint;
} {
    return {
        insufficientBalance: value.insufficientBalance,
        availableBalance: value.availableBalance,
        completedToday: value.completedToday,
        vipLevel: from_candid_VipLevel_n14(_uploadFile, _downloadFile, value.vipLevel),
        blocked: value.blocked,
        commissionEarned: value.commissionEarned,
        canStartTask: value.canStartTask,
        commissionRate: value.commissionRate,
        requestedRecharge: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.requestedRecharge)),
        pendingRefund: value.pendingRefund,
        dailyTaskQuota: value.dailyTaskQuota
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    body: string;
    userId: _UserId;
    createdAt: _Timestamp;
    fromAdmin: boolean;
    attachment: [] | [_Attachment];
}): Promise<{
    id: bigint;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    fromAdmin: boolean;
    attachment?: Attachment;
}> {
    return {
        id: value.id,
        body: value.body,
        userId: value.userId,
        createdAt: value.createdAt,
        fromAdmin: value.fromAdmin,
        attachment: record_opt_to_undefined(await from_candid_opt_n49(_uploadFile, _downloadFile, value.attachment))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    kind: _AttachmentKind;
    name: string;
    size: bigint;
}): Promise<{
    blob: ExternalBlob;
    kind: AttachmentKind;
    name: string;
    size: bigint;
}> {
    return {
        blob: await from_candid_ExternalBlob_n52(_uploadFile, _downloadFile, value.blob),
        kind: from_candid_AttachmentKind_n53(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        size: value.size
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: _VipLevel;
    commissionRate: bigint;
    dailyTaskQuota: bigint;
}): {
    level: VipLevel;
    commissionRate: bigint;
    dailyTaskQuota: bigint;
} {
    return {
        level: from_candid_VipLevel_n14(_uploadFile, _downloadFile, value.level),
        commissionRate: value.commissionRate,
        dailyTaskQuota: value.dailyTaskQuota
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskRecordView>): Array<TaskRecordView> {
    return value.map((x)=>from_candid_TaskRecordView_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminAccountRow>): Array<AdminAccountRow> {
    return value.map((x)=>from_candid_AdminAccountRow_n12(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessageView>): Promise<Array<ChatMessageView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ChatMessageView_n47(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalView>): Array<WithdrawalView> {
    return value.map((x)=>from_candid_WithdrawalView_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VipConfig>): Array<VipConfig> {
    return value.map((x)=>from_candid_VipConfig_n59(_uploadFile, _downloadFile, x));
}
function to_candid_AttachmentKind_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttachmentKind): _AttachmentKind {
    return value == AttachmentKind.video ? {
        video: null
    } : value == AttachmentKind.file ? {
        file: null
    } : value == AttachmentKind.image ? {
        image: null
    } : value;
}
async function to_candid_Attachment_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attachment): Promise<_Attachment> {
    return await to_candid_record_n63(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_RecordStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordStatus): _RecordStatus {
    return value == RecordStatus.termine ? {
        termine: null
    } : value == RecordStatus.soumission ? {
        soumission: null
    } : value == RecordStatus.frozen ? {
        frozen: null
    } : value;
}
function to_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_VipLevel_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VipLevel): _VipLevel {
    return value == VipLevel.vip0 ? {
        vip0: null
    } : value == VipLevel.vip1 ? {
        vip1: null
    } : value == VipLevel.vip2 ? {
        vip2: null
    } : value == VipLevel.vip3 ? {
        vip3: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordStatus | null): [] | [_RecordStatus] {
    return value === null ? candid_none() : candid_some(to_candid_RecordStatus_n57(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attachment | null): Promise<[] | [_Attachment]> {
    return value === null ? candid_none() : candid_some(await to_candid_Attachment_n62(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    kind: AttachmentKind;
    name: string;
    size: bigint;
}): Promise<{
    blob: _ExternalBlob;
    kind: _AttachmentKind;
    name: string;
    size: bigint;
}> {
    return {
        blob: await to_candid_ExternalBlob_n64(_uploadFile, _downloadFile, value.blob),
        kind: to_candid_AttachmentKind_n65(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        size: value.size
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
